### ISSUE TITLE
[FEATURE] 12_OrderDetail 화면 구현

### ISSUE THREAD

**Issue by hansh0101** [woowa-techcamp-2022/android-banchan-01#58]
## 📝  To-do

- [x] 주문 상세 내역 화면 UI 구현
- [x] 주문 상세 내역 화면 API 연결
- [ ] 주문 상세 내역 화면 배송 중 / 배송완료 조건 분기처리

## 📆 Date

0813 ~ 0813
