### ISSUE TITLE
[FEATURE] 16_RecentlyViewedProducts RecyclerView Item에 대한 이벤트 처리

### ISSUE THREAD

**Issue by hansh0101** [woowa-techcamp-2022/android-banchan-01#78]
## 📝  To-do

- [ ] 아이템 클릭 시 아이템 상세 화면으로 이동
- [ ] 아이템 장바구니 버튼 클릭 시 장바구니에 담기 구현
- [x] RecyclerView ItemDecoration 적용

## 📆 Date

0815 ~ 0815
