### ISSUE TITLE
[FEATURE] 11_Cart 화면 구현

### ISSUE THREAD

**Issue by hansh0101** [woowa-techcamp-2022/android-banchan-01#85]
## 📝  To-do

- [x] 11_Cart 화면 UI 구현
- [x] 11_Cart 화면 기능 구현
- [x] 11_Cart 화면 API 연결

## 합의완료

1. 상단의 체크 해제 + 삭제 부분 UI는 스크롤되지 않는 고정 영역이다.
2. RecyclerView 1개로 처리한다.
3. getItemCount()가 리턴하는 값은 실제 장바구니에 담긴 아이템 개수 + 2로 해서 구현한다.
4. 주문 금액 정보는 notifyItemChanged를 통해 클릭이 일어날 때마다 UI를 갱신한다.
5. 일단은 여기까지. 추후 더 합의된 사항이 있다면 Comment를 남겨 공동으로 이슈를 추적할 수 있게 한다.

## 📆 Date

0816 ~ 0818
